name: Publish ESP32 Library with Examples

on:
  push:
    tags:
      - "v*"  # 태그 기반 배포

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 저장소 체크아웃
      - name: Checkout code
        uses: actions/checkout@v3

      # 라이브러리와 예제 패키징
      - name: Package library and examples
        run: |
          mkdir -p package
          cp -r src examples library.properties README.md package/
          cd package
          zip -r ESP32-Git-OtaUpdate_Library.zip ./*

      # 패키지 업로드
      #- name: Upload to GitHub Packages
      #  uses: actions/upload-artifact@v3
      #  with:
      #    name: ESP32-Git-OtaUpdate_Library
      #    path: package/ESP32-Git-OtaUpdate_Library.zip

      # GitHub Release 생성 및 업로드
      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          body: "New release of the library."
          draft: false
          prerelease: false
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Release Assets
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./package
          asset_name: ESP32-Git-OtaUpdate_Library.zip
          asset_content_type: application/zip
