name: Release Arduino Library

on:
  release:
    types: [published]

permissions:
  contents: write  # GITHUB_TOKEN 권한 설정

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. 저장소 체크아웃
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. 라이브러리 패키지 준비
      - name: Prepare library package
        run: |
          mkdir -p package
          cp -R src/ examples/ library.properties README.md package/
          cd package
          zip -r ESP32-Git-OtaUpdate_Library.zip .

      # 3. Release에 패키지 업로드
      - name: Upload Release Asset
        uses: actions/upload-release-asset@v2
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./package/ESP32-Git-OtaUpdate_Library.zip
          asset_name: ESP32-Git-OtaUpdate_Library.zip
          asset_content_type: application/zip
